server:
  port: 8092

spring:
  datasource:
    url: jdbc:h2:file:./oauth2-login-h2-db
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          import_files: data.sql
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
      path: /h2-console
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    micro2:
      path: /micro2/**
      sensitiveHeaders:
      url: http://localhost:8094